'use strict';

window.AMS_MAP_DATA = Object.freeze({
  version: 1,
  centre: [4.8890, 52.3695],
  defaultHotel: {
    id: 'default-hotel',
    name: 'WestCord Fashion Hotel Amsterdam',
    address: 'Hendrikje Stoffelsstraat 1, 1058 GC Amsterdam',
    lat: 52.357545,
    lon: 4.844081
  },
  categories: [
    { id: 'major-landmark', label: 'Major landmarks', short: 'Major', colour: '#123fbd', text: '#ffffff', code: '★', defaultVisible: true, priority: 100 },
    { id: 'minor-landmark', label: 'Smaller landmarks', short: 'Minor', colour: '#4b6072', text: '#ffffff', code: '◆', defaultVisible: true, priority: 90 },
    { id: 'museum', label: 'Museums and galleries', short: 'Museum', colour: '#007fa3', text: '#ffffff', code: 'M', defaultVisible: true, priority: 80 },
    { id: 'activity', label: 'Activities, parks and markets', short: 'Activity', colour: '#c45100', text: '#ffffff', code: 'A', defaultVisible: true, priority: 70 },
    { id: 'adult', label: 'Adult museums, shops and shows', short: '18+', colour: '#8f268d', text: '#ffffff', code: '18', defaultVisible: true, priority: 60 },
    { id: 'food', label: 'Good-value food', short: 'Food', colour: '#d5a400', text: '#111111', code: '£', defaultVisible: true, priority: 50 },
    { id: 'coffee', label: 'Cannabis coffeeshops', short: 'Coffee', colour: '#087a43', text: '#ffffff', code: 'C', defaultVisible: true, priority: 40 },
    { id: 'smart', label: 'Smartshops', short: 'Smart', colour: '#b62a78', text: '#ffffff', code: 'S', defaultVisible: true, priority: 35 },
    { id: 'bars', label: 'Bars and pubs', short: 'Bar', colour: '#a72d32', text: '#ffffff', code: 'B', defaultVisible: true, priority: 30 },
    { id: 'shops', label: 'Budget food shops', short: 'Shop', colour: '#006fc4', text: '#ffffff', code: 'SH', defaultVisible: true, priority: 25 },
    { id: 'transport', label: 'Useful transport stops', short: 'Stop', colour: '#007c88', text: '#ffffff', code: 'T', defaultVisible: false, priority: 20 }
  ],
  places: [
    {id:'centraal',name:'Amsterdam Centraal',category:'major-landmark',importance:'major',code:'ST',address:'Stationsplein',lat:52.37817,lon:4.90056,note:'Main railway station and city-centre transport hub.'},
    {id:'royal-palace',name:'Royal Palace Amsterdam',category:'major-landmark',importance:'major',code:'RP',address:'Nieuwezijds Voorburgwal 147',lat:52.37316,lon:4.89162,note:'Major historic palace on Dam Square.'},
    {id:'rijksmuseum',name:'Rijksmuseum',category:'museum',importance:'major',code:'RM',address:'Museumstraat 1',lat:52.35999,lon:4.88522,note:'National museum of Dutch art and history.'},
    {id:'van-gogh',name:'Van Gogh Museum',category:'museum',importance:'major',code:'VG',address:'Museumplein 6',lat:52.35842,lon:4.88108,note:'Major Van Gogh collection.'},
    {id:'stedelijk',name:'Stedelijk Museum',category:'museum',importance:'major',code:'SM',address:'Museumplein 10',lat:52.35802,lon:4.87976,note:'Modern and contemporary art museum.'},
    {id:'anne-frank',name:'Anne Frank House',category:'major-landmark',importance:'major',code:'AF',address:'Westermarkt 20',lat:52.37522,lon:4.88398,note:'Historic house and museum.'},
    {id:'oude-kerk',name:'Oude Kerk',category:'major-landmark',importance:'major',code:'OK',address:'Oudekerksplein 23',lat:52.37437,lon:4.89808,note:'Amsterdam’s oldest building.'},
    {id:'nemo',name:'NEMO Science Museum',category:'museum',importance:'major',code:'NE',address:'Oosterdok 2',lat:52.37437,lon:4.91263,note:'Major interactive science museum.'},
    {id:'maritime',name:'National Maritime Museum',category:'museum',importance:'major',code:'MM',address:'Kattenburgerplein 1',lat:52.37175,lon:4.91428,note:'Dutch maritime-history museum.'},
    {id:'artis',name:'ARTIS Royal Zoo',category:'activity',importance:'major',code:'AZ',address:'Plantage Kerklaan 38–40',lat:52.36604,lon:4.91619,note:'Historic zoo and science campus.'},
    {id:'heineken',name:'Heineken Experience',category:'activity',importance:'major',code:'HX',address:'Stadhouderskade 78',lat:52.35798,lon:4.891,note:'Brewery visitor attraction.'},
    {id:'eye',name:'EYE Filmmuseum',category:'museum',importance:'major',code:'EY',address:'IJpromenade 1',lat:52.38402,lon:4.90057,note:'Film museum across the IJ.'},
    {id:'adam',name:"A'DAM Lookout",category:'activity',importance:'major',code:'AD',address:'Overhoeksplein 5',lat:52.38305,lon:4.90265,note:'Observation deck and tower.'},
    {id:'hart',name:"H'ART Museum",category:'museum',importance:'major',code:'HA',address:'Amstel 51',lat:52.36502,lon:4.90208,note:'Museum and exhibition venue.'},
    {id:'foodhallen',name:'Foodhallen / De Hallen',category:'activity',importance:'major',code:'FH',address:'Bellamyplein 51',lat:52.36785,lon:4.8687,note:'Indoor food hall and cultural complex.'},
    {id:'dam',name:'Dam Square',category:'minor-landmark',importance:'minor',code:'DS',address:'Dam',lat:52.37312,lon:4.8922,note:'Central city square.'},
    {id:'national-monument',name:'National Monument',category:'minor-landmark',importance:'minor',code:'NM',address:'Dam',lat:52.37282,lon:4.89318,note:'National remembrance monument.'},
    {id:'nieuwmarkt',name:'Nieuwmarkt & De Waag',category:'minor-landmark',importance:'minor',code:'NW',address:'Nieuwmarkt',lat:52.37257,lon:4.90028,note:'Historic square and former city gate.'},
    {id:'westerkerk',name:'Westerkerk',category:'minor-landmark',importance:'minor',code:'WK',address:'Prinsengracht 279',lat:52.37488,lon:4.88369,note:'Landmark church beside the Anne Frank House.'},
    {id:'begijnhof',name:'Begijnhof',category:'minor-landmark',importance:'minor',code:'BG',address:'Begijnhof',lat:52.3692,lon:4.89047,note:'Historic enclosed courtyard.'},
    {id:'rembrandtplein',name:'Rembrandtplein',category:'minor-landmark',importance:'minor',code:'RE',address:'Rembrandtplein',lat:52.36693,lon:4.89657,note:'Central nightlife square.'},
    {id:'leidseplein',name:'Leidseplein',category:'minor-landmark',importance:'minor',code:'LE',address:'Leidseplein',lat:52.36421,lon:4.88198,note:'Entertainment and theatre district.'},
    {id:'bloemenmarkt',name:'Flower Market',category:'activity',importance:'minor',code:'FM',address:'Singel',lat:52.36694,lon:4.89222,note:'Floating flower-market area.'},
    {id:'waterlooplein',name:'Waterlooplein Market',category:'activity',importance:'minor',code:'WM',address:'Waterlooplein',lat:52.36803,lon:4.9023,note:'Flea market and square.'},
    {id:'albert-cuyp',name:'Albert Cuyp Market',category:'activity',importance:'minor',code:'AC',address:'Albert Cuypstraat',lat:52.35558,lon:4.89553,note:'Large street market.'},
    {id:'museumplein',name:'Museumplein',category:'minor-landmark',importance:'minor',code:'MP',address:'Museumplein',lat:52.35791,lon:4.87906,note:'Museum district public space.'},
    {id:'moco',name:'Moco Museum',category:'museum',importance:'minor',code:'MO',address:'Honthorststraat 20',lat:52.3586,lon:4.88128,note:'Modern and contemporary art museum.'},
    {id:'hortus',name:'Hortus Botanicus',category:'activity',importance:'minor',code:'HB',address:'Plantage Middenlaan 2a',lat:52.36699,lon:4.90745,note:'Botanical garden.'},
    {id:'jewish-museum',name:'Jewish Museum',category:'museum',importance:'minor',code:'JM',address:'Nieuwe Amstelstraat 1',lat:52.36723,lon:4.90469,note:'Jewish history and culture museum.'},
    {id:'synagogue',name:'Portuguese Synagogue',category:'minor-landmark',importance:'minor',code:'PS',address:'Mr. Visserplein 3',lat:52.36739,lon:4.90484,note:'Seventeenth-century synagogue.'},
    {id:'magere-brug',name:'Magere Brug',category:'minor-landmark',importance:'minor',code:'MB',address:'Kerkstraat / Amstel',lat:52.36358,lon:4.90228,note:'Historic bridge over the Amstel.'},
    {id:'vondelpark',name:'Vondelpark',category:'activity',importance:'minor',code:'VP',address:'Vondelpark',lat:52.358,lon:4.86865,note:'Amsterdam’s best-known city park.'},
    {id:'dungeon',name:'Amsterdam Dungeon',category:'activity',importance:'minor',code:'DG',address:'Rokin 78',lat:52.36986,lon:4.89001,note:'Themed visitor attraction.'},
    {id:'body-worlds',name:'BODY WORLDS Amsterdam',category:'activity',importance:'minor',code:'BW',address:'Damrak 66',lat:52.37502,lon:4.89505,note:'Human-body exhibition.'},
    {id:'ripleys',name:"Ripley's Believe It or Not!",category:'activity',importance:'minor',code:'RI',address:'Dam 21',lat:52.37266,lon:4.89337,note:'Curiosity museum and attraction.'},
    {id:'nine-streets',name:'De 9 Straatjes',category:'activity',importance:'minor',code:'9S',address:'Nine Streets area',lat:52.37084,lon:4.88585,note:'Shopping streets in the canal belt.'},
    {id:'jordaan',name:'Jordaan',category:'minor-landmark',importance:'minor',code:'JO',address:'Jordaan district',lat:52.375,lon:4.8785,note:'Historic canal-side neighbourhood.'},
    {id:'sexmuseum',name:'Sexmuseum Amsterdam Venustempel',category:'adult',code:'18M',address:'Damrak 18',lat:52.37713,lon:4.89728,note:'Adult-history museum; 18+.'},
    {id:'red-secrets',name:'Red Light Secrets',category:'adult',code:'18M',address:'Oudezijds Achterburgwal 60',lat:52.37373,lon:4.8991,note:'Museum of prostitution in a former canal-house brothel; 18+.'},
    {id:'erotic-museum',name:'Erotic Museum',category:'adult',code:'18M',address:'Oudezijds Achterburgwal 54',lat:52.37391,lon:4.89921,note:'Erotic-art and history museum; 18+.'},
    {id:'condomerie',name:'Condomerie',category:'adult',code:'18S',address:'Warmoesstraat 141',lat:52.37402,lon:4.89653,note:'Specialist adult shop.'},
    {id:'mister-b',name:'Mister B Amsterdam',category:'adult',code:'18S',address:'Prinsengracht 192',lat:52.37436,lon:4.8832,note:'Fetish and leather shop; 18+.'},
    {id:'mail-female',name:'Mail & Female',category:'adult',code:'18S',address:'Nieuwe Vijzelstraat 2',lat:52.35953,lon:4.8875,note:'Sex-positive boutique; 18+.'},
    {id:'pure-lust',name:'Pure Lust Candy Store',category:'adult',code:'18S',address:'Oudezijds Voorburgwal 135',lat:52.37187,lon:4.89752,note:'Adult shop in De Wallen; 18+.'},
    {id:'star-shop',name:'Star Shop',category:'adult',code:'18S',address:'Oudekennissteeg 9',lat:52.37379,lon:4.89914,note:'BDSM-focused adult shop; 18+.'},
    {id:'casa-rosso',name:'Casa Rosso',category:'adult',code:'18A',address:'Oudezijds Achterburgwal 106–108',lat:52.37239,lon:4.89938,note:'Adult theatre; 18+.'},
    {id:'bananenbar',name:'Bananenbar',category:'adult',code:'18A',address:'Oudezijds Achterburgwal 37',lat:52.37437,lon:4.89955,note:'Adult bar/show venue; 18+.'},
    {id:'peepshow',name:'Sex Palace Peepshow',category:'adult',code:'18A',address:'Oudezijds Achterburgwal 84',lat:52.37324,lon:4.89927,note:'Peepshow venue; 18+.'},
    {id:'sexy-loo',name:'Sexy Loo',category:'adult',code:'18A',address:'Oudezijds Achterburgwal 86',lat:52.37315,lon:4.89929,note:'Novelty adult attraction; 18+.'},
    {id:'theater-97',name:'Theater 97',category:'adult',code:'18A',address:'Oudezijds Achterburgwal 97',lat:52.37268,lon:4.89934,note:'Adult entertainment venue; 18+.'},
    {id:'grey-area',name:'Grey Area',category:'coffee',code:'C',address:'Oude Leliestraat 2',lat:52.37436,lon:4.88627,note:'Licensed cannabis coffeeshop; 18+. Carry ID.'},
    {id:'boerejongens-centre',name:'Boerejongens Centrum',category:'coffee',code:'C',address:'Utrechtsestraat 21',lat:52.36691,lon:4.9002,note:'Licensed cannabis coffeeshop; 18+. Carry ID.'},
    {id:'green-house-centre',name:'Green House Centrum',category:'coffee',code:'C',address:'Oudezijds Voorburgwal 191',lat:52.37065,lon:4.89758,note:'Licensed cannabis coffeeshop in a canal house; 18+.'},
    {id:'dampkring',name:'Original Dampkring',category:'coffee',code:'C',address:'Handboogstraat 29',lat:52.36848,lon:4.88912,note:'Licensed cannabis coffeeshop; 18+.'},
    {id:'siberie',name:'Coffeeshop Siberië',category:'coffee',code:'C',address:'Brouwersgracht 11',lat:52.3802,lon:4.89166,note:'Licensed cannabis coffeeshop; 18+.'},
    {id:'coffeeshop-amsterdam',name:'Coffeeshop Amsterdam',category:'coffee',code:'C',address:'Haarlemmerstraat 44',lat:52.37934,lon:4.89337,note:'Licensed cannabis coffeeshop; 18+.'},
    {id:'barneys',name:"Barney's Coffeeshop",category:'coffee',code:'C',address:'Haarlemmerstraat 102',lat:52.38007,lon:4.88938,note:'Licensed cannabis coffeeshop; 18+.'},
    {id:'tweede-kamer',name:'De Tweede Kamer',category:'coffee',code:'C',address:'Heisteeg 6',lat:52.36962,lon:4.88927,note:'Licensed cannabis coffeeshop; 18+.'},
    {id:'when-nature-calls',name:'When Nature Calls',category:'smart',code:'S',address:'Keizersgracht 508',lat:52.36485,lon:4.88473,note:'Smartshop selling legal products including truffles; 18+. Follow staff guidance.'},
    {id:'kokopelli',name:'Kokopelli',category:'smart',code:'S',address:'Warmoesstraat 12',lat:52.37699,lon:4.89844,note:'Smartshop; 18+. Follow staff guidance.'},
    {id:'tatanka',name:'Tatanka Smartshop',category:'smart',code:'S',address:'Korte Leidsedwarsstraat 151A',lat:52.36386,lon:4.88172,note:'Smartshop; 18+. Follow staff guidance.'},
    {id:'magic-mushroom-gallery',name:'Magic Mushroom Gallery',category:'smart',code:'S',address:'Singel 524',lat:52.36456,lon:4.89145,note:'Smartshop; 18+. Follow staff guidance.'},
    {id:'vleminckx',name:'Vleminckx de Sausmeester',category:'food',code:'NL',cuisine:'Dutch fries',address:'Voetboogstraat 33',lat:52.36815,lon:4.8895,note:'Strong-value takeaway fries.'},
    {id:'caldi-freddi',name:'Caldi e Freddi',category:'food',code:'IT',cuisine:'Italian deli',address:'Spuistraat 102',lat:52.37455,lon:4.88915,note:'Strong-value slices and sandwiches.'},
    {id:'wigboldus',name:'Rob Wigboldus Vishandel',category:'food',code:'SE',cuisine:'Seafood',address:'Zoutsteeg 6',lat:52.37537,lon:4.89448,note:'Fish sandwiches and herring.'},
    {id:'broodje-bert',name:'Broodje Bert',category:'food',code:'SW',cuisine:'Sandwiches',address:'Singel 321',lat:52.37082,lon:4.88842,note:'Generously filled sandwiches.'},
    {id:'hapjeshoek',name:'De Hapjeshoek',category:'food',code:'SR',cuisine:'Surinamese',address:'Waterlooplein 6',lat:52.36812,lon:4.90292,note:'Strong-value Surinamese takeaway.'},
    {id:'van-dobben',name:'Eetsalon Van Dobben',category:'food',code:'NL',cuisine:'Dutch snacks',address:'Korte Reguliersdwarsstraat 5–9',lat:52.36642,lon:4.8945,note:'Croquettes and sandwiches.'},
    {id:'tjin',name:"Tjin's Exotische Broodjes",category:'food',code:'HK',cuisine:'Hakka / Surinamese',address:'Van Woustraat 17',lat:52.35683,lon:4.90024,note:'Filled rolls and hot dishes.'},
    {id:'febo',name:'FEBO Nieuwendijk',category:'food',code:'FF',cuisine:'Dutch fast food',address:'Nieuwendijk 50',lat:52.37629,lon:4.89536,note:'Low-cost snack option.'},
    {id:'omelegg',name:'Omelegg City Centre',category:'food',code:'BR',cuisine:'Breakfast',address:'Nieuwebrugsteeg 24',lat:52.37707,lon:4.89859,note:'Breakfast-value pick.'},
    {id:'bird-thai',name:'Bird Thai Snackbar',category:'food',code:'TH',cuisine:'Thai',address:'Zeedijk 77',lat:52.37461,lon:4.9004,note:'Strong-value Thai pick.'},
    {id:'new-king',name:'New King',category:'food',code:'CN',cuisine:'Chinese',address:'Zeedijk 115–117',lat:52.37394,lon:4.90134,note:'Affordable Chinese option.'},
    {id:'ramen-ya',name:'Ramen-Ya',category:'food',code:'JP',cuisine:'Japanese ramen',address:'Oudezijds Voorburgwal 236',lat:52.36983,lon:4.89766,note:'Central ramen pick.'},
    {id:'samrat',name:'Samrat',category:'food',code:'IN',cuisine:'Indian',address:'Bethaniendwarsstraat 17',lat:52.37211,lon:4.89979,note:'Central Indian option.'},
    {id:'maoz',name:'Maoz Vegetarian',category:'food',code:'ME',cuisine:'Middle Eastern vegetarian',address:'Leidsestraat 85',lat:52.36435,lon:4.88318,note:'Quick-value vegetarian option.'},
    {id:'los-pilones',name:'Los Pilones',category:'food',code:'MX',cuisine:'Mexican',address:'Kerkstraat 63',lat:52.3657,lon:4.88725,note:'Central Mexican option; compare current menu prices.'},
    {id:'golden-temple',name:'Golden Temple',category:'food',code:'VG',cuisine:'Vegan / vegetarian',address:'Utrechtsestraat 126',lat:52.3627,lon:4.90079,note:'Plant-based cuisine option.'},
    {id:'cafe-hoppe',name:'Café Hoppe',category:'bars',code:'PB',address:'Spui 18-20',lat:52.36868,lon:4.88945,note:'Historic brown café.'},
    {id:'cafe-de-dokter',name:'Café de Dokter',category:'bars',code:'PB',address:'Rozenboomsteeg 4',lat:52.37054,lon:4.88991,note:'Tiny historic Amsterdam bar.'},
    {id:'proeflokaal-arendsnest',name:'Proeflokaal Arendsnest',category:'bars',code:'PB',address:'Herengracht 90',lat:52.37661,lon:4.88691,note:'Dutch beer bar.'},
    {id:'waterhole',name:'The Waterhole',category:'bars',code:'BAR',address:'Korte Leidsedwarsstraat 49',lat:52.36389,lon:4.88348,note:'Live-music bar.'},
    {id:'molly-malone',name:"Molly Malone's Irish Pub",category:'bars',code:'PB',address:'Oudezijds Kolk 9',lat:52.37679,lon:4.90091,note:'Irish pub near Centraal.'},
    {id:'spar-weteringschans',name:'SPAR city Weteringschans',category:'shops',code:'SP',address:'Weteringschans 165',lat:52.36069,lon:4.88696,note:'Convenience food, drinks and sandwich options.'},
    {id:'spar-nieuwezijds',name:'SPAR city Nieuwezijds',category:'shops',code:'SP',address:'Nieuwezijds Voorburgwal 55',lat:52.37577,lon:4.89272,note:'Convenience food and snacks.'},
    {id:'albert-heijn-jodenbreestraat',name:'Albert Heijn Jodenbreestraat',category:'shops',code:'AH',address:'Jodenbreestraat 21',lat:52.36942,lon:4.90309,note:'Supermarket for cheap snacks, drinks and meal deals.'},
    {id:'albert-heijn-museumplein',name:'Albert Heijn Museumplein',category:'shops',code:'AH',address:'Cornelis Schuytstraat area',lat:52.35702,lon:4.87765,note:'Supermarket near Museumplein.'},
    {id:'dirk-warmoesstraat',name:'Dirk van den Broek Warmoesstraat',category:'shops',code:'DK',address:'Warmoesstraat 120',lat:52.3748,lon:4.89711,note:'Budget supermarket.'},
    {id:'stop-centraal',name:'Amsterdam Centraal transport stop',category:'transport',code:'T',address:'Stationsplein',lat:52.37817,lon:4.90056,note:'Major city-centre transport interchange.'},
    {id:'stop-dam',name:'Dam / Paleisstraat stop',category:'transport',code:'T',address:'Dam',lat:52.37293,lon:4.89135,note:'Central tram stop.'},
    {id:'stop-leidse',name:'Leidseplein stop',category:'transport',code:'T',address:'Leidseplein',lat:52.36421,lon:4.88198,note:'Useful central tram stop.'},
    {id:'stop-weesper',name:'Weesperplein stop',category:'transport',code:'T',address:'Weesperplein',lat:52.36103,lon:4.90612,note:'Metro and tram interchange.'},
    {id:'stop-suriname',name:'Surinameplein stop',category:'transport',code:'T',address:'Surinameplein',lat:52.35784,lon:4.84818,note:'Useful for the default hotel.'},
    {id:'stop-lelylaan',name:'Amsterdam Lelylaan',category:'transport',code:'T',address:'Cornelis Lelylaan',lat:52.35722,lon:4.83389,note:'Rail, metro and tram interchange.'}
  ]
});
